version: "2"
services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    ports:
      - 3306
    volumes:
      - "./mysql/data/:/var/lib/mysql/"
    env_file:
      - ./mysql.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    container_name: phpmyadmin
    env_file:
      - ./phpmyadmin.env
    links:
      - mysql
    restart: always

  pydio:
    image: metabase/metabase:v0.34.3
    container_name: metabase
    volumes:
      - "metabase-data:/metabase-data"
    ports:
      - "3000"
    env_file:
      - ./metabase.env
    restart: always

  proxy:
    image: nginx:1.17.9-alpine
    container_name: proxy
    volumes:
      - "./proxy/conf.d/:/etc/nginx/conf.d/"
      - "./proxy/html/:/usr/share/nginx/html/"
      - "./proxy/log/:/var/log/nginx/"
    ports:
      - 80:80
    restart: always

volumes:
  metabase-data:
    driver: local

networks:
  default:
    external:
      name: shared
