version: "2"
services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql/
  #   env_file:
  #     - ./mysql.env
  #   command: --default-authentication-plugin=mysql_native_password
  #   cap_add:
  #     - SYS_NICE
  #   restart: always

  # mysql:
  #   image: mariadb:10.5
  #   container_name: mysql
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mariadb/data:/var/lib/mysql/
  #   env_file:
  #     - ./mysql.env
  #   restart: always

  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql/
    env_file:
      - ./mysql.env
    restart: always
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:5.0.2-fpm-alpine
  #   container_name: phpmyadmin
  #   volumes:
  #     - phpmyadmin_data:/var/www/html/
  #   env_file:
  #     - ./phpmyadmin.env
  #   restart: always

  # pma_nginx:
  #   image: nginx:1.17.9-alpine
  #   container_name: pma_nginx
  #   volumes:
  #     - ./pma_nginx/conf.d/pma.conf:/etc/nginx/conf.d/default.conf:ro
  #     - phpmyadmin_data:/var/www/html/
  #   environment:
  #     TZ: Asia/Tokyo
  #   restart: always

  proxy:
    image: nginx:1.17.9-alpine
    container_name: proxy
    volumes:
      - "./proxy/conf.d/:/etc/nginx/conf.d/"
      - "./proxy/html/:/usr/share/nginx/html/"
      - "./proxy/log/:/var/log/nginx/"
      - "./proxy/certs/:/etc/nginx/certs/"
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Tokyo
    restart: always

volumes:
  mysql_data:
  # phpmyadmin_data:

networks:
  default:
    external:
      name: shared
