# version: "2"
version: "3"

services:
  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql/
    env_file:
      - ./mysql.env
    restart: always
  
  proxy:
    image: nginx:1.17.9-alpine
    container_name: proxy
    volumes:
      # - "./proxy/conf.d/:/etc/nginx/conf.d/"
      - "./proxy/html/:/usr/share/nginx/html/"
      - "./proxy/log/:/var/log/nginx/"
      - "./proxy/certs/:/etc/nginx/certs/"
    # ports:
    #   - 80:80
    #   - 443:443
    environment:
      TZ: Asia/Tokyo
    restart: always

volumes:
  mysql_data:

networks:
  default:
    external:
      name: shared
