version: "2"
services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    ports:
      - 3306
    volumes:
      - "./mysql/data/:/var/lib/mysql/"
    env_file:
      - ./mysql.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1-fpm-alpine
    container_name: phpmyadmin
    volumes:
      - phpmyadmin_data:/var/www/html/
      - "./pma/conf.d/:/usr/local/etc/php/conf.d/"
    env_file:
      - ./phpmyadmin.env
    restart: always

  pma_nginx:
    image: nginx:1.17.9-alpine
    container_name: pma_nginx
    volumes:
      - ./pma_nginx/conf.d/pma.conf:/etc/nginx/conf.d/default.conf:ro
      - phpmyadmin_data:/var/www/html/:ro
    restart: always

  # pydio:
  #   image: metabase/metabase:v0.34.3
  #   container_name: metabase
  #   volumes:
  #     - "metabase-data:/metabase-data"
  #   ports:
  #     - "3000"
  #   env_file:
  #     - ./metabase.env
  #   restart: always

  proxy:
    image: nginx:1.17.9-alpine
    container_name: proxy
    volumes:
      - "./proxy/conf.d/:/etc/nginx/conf.d/"
      - "./proxy/html/:/usr/share/nginx/html/"
      - "./proxy/log/:/var/log/nginx/"
      - "./proxy/certs/:/etc/nginx/certs/"
    ports:
      - 80:80
      - 443:443
    restart: always

volumes:
  # metabase-data:
  #   driver: local
  phpmyadmin_data:

networks:
  default:
    external:
      name: shared
